Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,6 +1,4 @@
-# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
-# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
-name: CMake on a single platform
+name:  Unit tests
 
 on: push
 
@@ -10,9 +8,6 @@ env:
 
 jobs:
   build:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
     runs-on: ubuntu-latest
 
     steps:
@@ -28,13 +23,13 @@ jobs:
       run: ./buildGenerator 
 
     - name: Test
-      run: ./runTests --gtest_output="xml:report.xml"
+      run: ./runTests
 
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: GTEST
-        path: Generator/source/build/tests/*.xml
-        reporter: java-junit
-        fail-on-error: true
+    # - name: Test Report
+    #   uses: dorny/test-reporter@v1
+    #   if: success() || failure()
+    #   with:
+    #     name: GTEST
+    #     path: Generator/source/build/tests/*.xml
+    #     reporter: java-junit
+    #     fail-on-error: true
